version: '3.6'
services:
  nginx-setup:
    container_name: setup-nginx
    image: "metadatacenter/cedar-setup-nginx:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-setup-nginx
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NGINX_HTTP_PORT}:80
    volumes:
      - log_nginx:/etc/nginx/log
      - cedar_cert:/etc/letsencrypt
    environment:
      - CEDAR_HOST

networks:
  cedarnet:
      name: cedarnet
      external: true

volumes:
  log_nginx:
    name: log_nginx
  cedar_cert:
    name: cedar_cert
    external: true
