version: '3.6'
services:
  frontend-main:
    container_name: frontend-main
    image: "metadatacenter/cedar-frontend-main:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-frontend-main
    networks:
      cedarnet:
        ipv4_address: ${CEDAR_FRONTEND_EDITOR_HOST}
    ports:
      - "${CEDAR_FRONTEND_EDITOR_PORT}:4200"
    volumes:
      - log_frontend_main:/log
    environment:
      - CEDAR_HOST
  frontend-component:
    container_name: frontend-component
    image: "metadatacenter/cedar-frontend-component:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-frontend-component
    networks:
      cedarnet:
        ipv4_address: ${CEDAR_FRONTEND_COMPONENT_HOST}
    ports:
      - "${CEDAR_FRONTEND_COMPONENT_PORT}:4240"
    volumes:
      - log_frontend_component:/log
    environment:
      - CEDAR_HOST
  frontend-openview:
    container_name: frontend-openview
    image: "metadatacenter/cedar-frontend-openview:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-frontend-openview
    networks:
      cedarnet:
        ipv4_address: ${CEDAR_FRONTEND_OPENVIEW_HOST}
    ports:
      - "${CEDAR_FRONTEND_OPENVIEW_PORT}:4220"
    volumes:
      - log_frontend_openview:/log
    environment:
      - CEDAR_HOST
  frontend-monitoring:
    container_name: frontend-monitoring
    image: "metadatacenter/cedar-frontend-monitoring:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-frontend-monitoring
    networks:
      cedarnet:
        ipv4_address: ${CEDAR_FRONTEND_MONITORING_HOST}
    ports:
      - "${CEDAR_FRONTEND_MONITORING_PORT}:4300"
    volumes:
      - log_frontend_monitoring:/log
    environment:
      - CEDAR_HOST
  frontend-artifacts:
    container_name: frontend-artifacts
    image: "metadatacenter/cedar-frontend-artifacts:${CEDAR_DOCKER_VERSION}"
    build: ../../cedar-docker-build/cedar-frontend-artifacts
    networks:
      cedarnet:
        ipv4_address: ${CEDAR_FRONTEND_ARTIFACTS_HOST}
    ports:
      - "${CEDAR_FRONTEND_ARTIFACTS_PORT}:4320"
    volumes:
      - log_frontend_artifacts:/log
    environment:
      - CEDAR_HOST

networks:
  cedarnet:
    name: cedarnet
    external: true

volumes:
  log_frontend_main:
    name: log_frontend_main
  log_frontend_component:
    name: log_frontend_component
  log_frontend_openview:
    name: log_frontend_openview
  log_frontend_monitoring:
    name: log_frontend_monitoring
  log_frontend_artifacts:
    name: log_frontend_artifacts
